[Default]
LogLevel = info
SSL = True

[default]
Homeserver = https://matrix-client.matrix.org
ListenAddress = 0.0.0.0
ListenPort = 8008
SSL = False
UseKeyring = False
IgnoreVerification = True
DropOldKeys = False
