# SSH Host Connection Matrix
# Last Updated: 2025-12-27
# Defines all SSH targets with primary/fallback connection paths

hosts:
  garzahive:
    description: "GarzaHive-02 DigitalOcean VPS (SFO3)"
    primary:
      host: "64.227.106.134"
      user: "root"
      port: 22
      key_name: "ssh_garzahive"
      test_command: "uptime"
      timeout: 10
    
    fallbacks:
      - method: "ssh_relay_via_mac"
        description: "SSH through Mac as jump host"
        command: "ssh -J customer@ssh.garzahive.com root@64.227.106.134"
      
      - method: "lrlab_mcp_tool"
        description: "Use Last Rock Dev MCP ssh_exec tool"
        mcp: "lrlab-mcp"
        tool: "ssh_exec"
        params:
          host: "garzahive"
      
      - method: "cf_mcp_tool"
        description: "Use CF MCP ssh_exec tool"
        mcp: "cf-mcp"
        tool: "ssh_exec"
        params:
          host: "garzahive"
      
      - method: "digitalocean_api"
        description: "Last resort: reboot via DO API and retry"
        script: "scripts/ssh/do-emergency-reboot.sh"
        droplet_id: "check DO dashboard"
    
    services:
      - "garza-hive-mcp"
      - "task-supervisor"
      - "docker"
    
    health_check:
      command: "docker ps --format '{{.Names}}' 2>/dev/null | wc -l"
      expected_min: 1
      interval_seconds: 300

  mac:
    description: "Remote Mac via Cloudflare Tunnel"
    primary:
      host: "ssh.garzahive.com"
      user: "customer"
      port: 22
      key_name: "ssh_mac"
      test_command: "echo $HOME"
      timeout: 10
    
    fallbacks:
      - method: "cf_mcp_shell"
        description: "CF MCP is running ON this machine - use shell_exec"
        mcp: "cf-mcp"
        tool: "shell_exec"
      
      - method: "desktop_commander"
        description: "Desktop Commander MCP (if connected)"
        note: "Desktop Commander runs on this Mac"
    
    services:
      - "cf-mcp"
      - "computer-use-containers"
      - "beeper-sync"
    
    health_check:
      command: "ps aux | grep -E 'mcp|node' | wc -l"
      expected_min: 2
      interval_seconds: 300

  boulder:
    description: "Mac mini Boulder via Cloudflare Tunnel"
    primary:
      host: "boulder-ssh.garzahive.com"
      user: "jadengarza"
      port: 22
      key_name: "ssh_boulder"
      test_command: "hostname"
      timeout: 10
    
    fallbacks:
      - method: "local_network"
        description: "Direct LAN access if on same network"
        host: "192.168.4.81"
        user: "jadengarza"
    
    services:
      - "home-assistant"
      - "mosquitto-mqtt"
    
    health_check:
      command: "docker ps | grep -E 'homeassistant|mosquitto' | wc -l"
      expected_min: 1
      interval_seconds: 300

  n8n:
    description: "N8N VPS (DigitalOcean)"
    primary:
      host: "167.172.147.240"
      user: "root"
      port: 22
      key_name: "ssh_n8n"
      test_command: "uptime"
      timeout: 10
    
    fallbacks:
      - method: "lrlab_mcp_tool"
        mcp: "lrlab-mcp"
        tool: "ssh_exec"
        params:
          host: "n8n"
    
    services:
      - "n8n"
    
    health_check:
      command: "curl -s http://localhost:5678/healthz 2>/dev/null || echo 'down'"
      expected: "ok"
      interval_seconds: 300

  octelium:
    description: "Octelium Zero Trust Gateway (DigitalOcean NYC1)"
    primary:
      host: "68.183.108.79"
      user: "root"
      port: 22
      key_name: "ssh_octelium"
      test_command: "uptime"
      timeout: 10
    
    services:
      - "octelium-gateway"
      - "cloudflared"
    
    health_check:
      command: "systemctl is-active cloudflared"
      expected: "active"
      interval_seconds: 300

# Global SSH Configuration
ssh_config:
  default_timeout: 10
  retry_attempts: 3
  retry_delay_seconds: 2
  strict_host_key_checking: false
  
  # Key locations (relative to repo or absolute paths)
  key_paths:
    ssh_garzahive: "~/.ssh/id_rsa_garzahive"
    ssh_mac: "~/.ssh/id_rsa"
    ssh_boulder: "~/.ssh/id_rsa_boulder"
    ssh_n8n: "~/.ssh/id_rsa_n8n"
    ssh_octelium: "~/.ssh/id_rsa_octelium"

# Connection Priority Rules
connection_rules:
  prefer_direct: true
  auto_fallback: true
  log_all_attempts: true
  notify_on_fallback: false
  notify_on_all_methods_failed: true
