# SSH Connection Matrix
# Complete inventory of all accessible hosts with fallback paths

version: "1.0.0"
last_updated: "2025-12-27"

hosts:
  garzahive:
    description: "GarzaHive-02 DigitalOcean VPS (Legacy)"
    primary:
      host: 64.227.106.134
      user: root
      port: 22
      key_name: ssh_garzahive
      test_command: "uptime"
    
    fallbacks:
      - method: ssh_via_mac
        description: "SSH relay through Mac"
        command: "ssh -J customer@ssh.garzahive.com root@64.227.106.134"
      
      - method: mcp_tool
        description: "Via Last Rock Dev MCP ssh_exec"
        mcp_server: lrlab-mcp
        tool: ssh_exec
        host_alias: garzahive
      
      - method: digitalocean_api
        description: "Reboot via DO API and retry"
        requires: do_api_token
    
    health_check:
      command: "docker ps"
      expected_contains: "Up"
      interval_seconds: 300
    
    status: phasing_out

  mac:
    description: "Remote Mac via Cloudflare Tunnel"
    primary:
      host: ssh.garzahive.com
      user: customer
      port: 22
      test_command: "hostname"
    
    fallbacks:
      - method: local_access
        description: "Direct access if on same network"
        host: 192.168.4.81
    
    health_check:
      command: "ps aux | grep mcp"
      expected_contains: "node"
      interval_seconds: 300
    
    status: active
    role: "CF MCP host, primary orchestrator"

  boulder:
    description: "Mac mini Boulder via CF Tunnel"
    primary:
      host: boulder-ssh.garzahive.com
      user: jadengarza
      port: 22
      test_command: "hostname"
    
    fallbacks:
      - method: local_access
        description: "Direct if on home network"
        host: 192.168.4.81
    
    status: active
    role: "Home server, Home Assistant"

  n8n:
    description: "N8N VPS Server"
    primary:
      host: 167.172.147.240
      user: root
      port: 22
      key_name: ssh_n8n
      test_command: "docker ps | grep n8n"
    
    fallbacks:
      - method: mcp_tool
        mcp_server: lrlab-mcp
        tool: ssh_exec
        host_alias: n8n
    
    health_check:
      command: "curl -s http://localhost:5678/healthz"
      expected_contains: "ok"
      interval_seconds: 300
    
    status: active

  octelium:
    description: "Octelium Zero Trust Gateway"
    primary:
      host: 68.183.108.79
      user: root
      port: 22
      key_name: ssh_octelium
      test_command: "systemctl status cloudflared"
    
    status: active
    role: "Zero trust gateway for homelab"

# Connection strategy rules
connection_strategy:
  retry_attempts: 3
  retry_delay_seconds: 5
  timeout_seconds: 30
  
  # Always try in this order
  priority:
    - primary
    - fallback[0]  # First fallback
    - fallback[1]  # Second fallback
    - fallback[2]  # Last resort

# SSH key locations (references to secrets)
ssh_keys:
  ssh_garzahive:
    location: craft_doc
    doc_id: "7061"
    field: "SSH Private Keys"
  
  ssh_n8n:
    location: craft_doc
    doc_id: "7061"
    field: "SSH Private Keys"
  
  ssh_octelium:
    location: craft_doc
    doc_id: "7061"
    field: "SSH Private Keys"

# MCP tool SSH mapping
mcp_ssh_tools:
  cf_mcp:
    available_hosts:
      - garzahive
      - mac
      - boulder
      - n8n
    tool_name: ssh_exec
  
  lrlab_mcp:
    available_hosts:
      - garzahive
      - mac
      - n8n
    tool_name: ssh_exec

# API fallbacks
api_fallbacks:
  digitalocean:
    endpoint: "https://api.digitalocean.com/v2"
    token_location: craft_doc
    doc_id: "7061"
    actions:
      - reboot_droplet
      - get_droplet_status
